// Renders the image-based docker-compose.yml from persisted config.
//
// Concrete values (ports, secrets, connection URLs) are NOT inlined here — the
// compose file only references ${VARS} that docker compose resolves from the
// sibling .env (see env.ts). That keeps secrets out of the compose file and
// lets the same .env drive both interpolation and our own bookkeeping.
import YAML from "yaml";
import type { ProjectConfig } from "./config.js";

/** Docker Hub image prefix; per-service repos are `${IMAGE_PREFIX}-<service>`
 *  (e.g. mickyarun/bodhiorchard-backend). */
export const IMAGE_PREFIX = "mickyarun/bodhiorchard";

const HOST_INTERNAL = "host.docker.internal:host-gateway";

type ComposeService = Record<string, unknown>;

function postgresService(): ComposeService {
  return {
    image: "pgvector/pgvector:pg16",
    environment: {
      POSTGRES_USER: "bodhiorchard",
      POSTGRES_PASSWORD: "bodhiorchard",
      POSTGRES_DB: "bodhiorchard",
    },
    volumes: ["postgres_data:/var/lib/postgresql/data"],
    ports: ["${POSTGRES_HOST_PORT}:5432"],
    healthcheck: {
      test: ["CMD-SHELL", "pg_isready -U bodhiorchard -d bodhiorchard"],
      interval: "3s",
      timeout: "3s",
      retries: 15,
    },
  };
}

function redisService(): ComposeService {
  return {
    image: "redis:7-alpine",
    ports: ["${REDIS_HOST_PORT}:6379"],
    healthcheck: {
      test: ["CMD", "redis-cli", "ping"],
      interval: "5s",
      timeout: "5s",
      retries: 5,
    },
  };
}

function backendService(config: ProjectConfig): ComposeService {
  const dependsOn: Record<string, { condition: string }> = {};
  if (config.services.postgres.mode === "bundled") {
    dependsOn.postgres = { condition: "service_healthy" };
  }
  if (config.services.redis.mode === "bundled") {
    dependsOn.redis = { condition: "service_healthy" };
  }

  const reusesInfra =
    config.services.postgres.mode === "reuse" || config.services.redis.mode === "reuse";

  const service: ComposeService = {
    image: `${IMAGE_PREFIX}-backend:\${IMAGE_TAG}`,
    environment: {
      DATABASE_URL: "${DATABASE_URL}",
      REDIS_URL: "${REDIS_URL}",
      SECRET_KEY: "${SECRET_KEY}",
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}",
      ACCESS_TOKEN_EXPIRE_MINUTES: "60",
      EMBEDDING_PROVIDER: "fastembed",
      EMBEDDING_MODEL: "BAAI/bge-small-en-v1.5",
      EMBEDDING_DIMENSIONS: "384",
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY:-}",
      LLM_PROVIDER: "${LLM_PROVIDER:-anthropic}",
      LLM_MODEL: "${LLM_MODEL:-claude-haiku-4-5-20251001}",
      LLM_PREMIUM_MODEL: "${LLM_PREMIUM_MODEL:-claude-sonnet-4-6}",
      COLYSEUS_URL: "http://multiplayer:2567",
      COLYSEUS_BRIDGE_SECRET: "${COLYSEUS_BRIDGE_SECRET}",
    },
    ports: ["${BACKEND_HOST_PORT}:8000"],
    volumes: ["repos_data:/data/repos", "ssh_data:/data/ssh"],
  };
  if (Object.keys(dependsOn).length > 0) service.depends_on = dependsOn;
  // Needed on Linux so the container can reach a host-run Postgres/Redis.
  if (reusesInfra) service.extra_hosts = [HOST_INTERNAL];
  return service;
}

function multiplayerService(): ComposeService {
  return {
    image: `${IMAGE_PREFIX}-multiplayer:\${IMAGE_TAG}`,
    depends_on: ["backend"],
    environment: {
      BACKEND_URL: "http://backend:8000",
      COLYSEUS_BRIDGE_SECRET: "${COLYSEUS_BRIDGE_SECRET}",
    },
    ports: ["${MULTIPLAYER_HOST_PORT}:2567"],
  };
}

function frontendService(): ComposeService {
  return {
    image: `${IMAGE_PREFIX}-frontend:\${IMAGE_TAG}`,
    depends_on: ["backend", "multiplayer"],
    ports: ["${FRONTEND_HOST_PORT}:80"],
  };
}

/** Build the compose document as a YAML string. Reused infra services are
 *  omitted entirely; their volumes drop with them. */
export function renderComposeFile(config: ProjectConfig): string {
  const services: Record<string, ComposeService> = {};
  const volumes: Record<string, null> = { repos_data: null, ssh_data: null };

  if (config.services.postgres.mode === "bundled") {
    services.postgres = postgresService();
    volumes.postgres_data = null;
  }
  if (config.services.redis.mode === "bundled") {
    services.redis = redisService();
  }
  services.backend = backendService(config);
  services.multiplayer = multiplayerService();
  services.frontend = frontendService();

  const header =
    "# Generated by `bodhiorchard init` — edit .bodhiorchard/config.json and\n" +
    "# re-run `bodhiorchard init` instead of hand-editing this file.\n";
  return header + YAML.stringify({ services, volumes });
}
