<template>
  <div class="pa-6">
    <!-- Loading -->
    <div v-if="prdStore.loading" class="d-flex justify-center py-12">
      <v-progress-circular indeterminate color="primary" />
    </div>

    <!-- Error -->
    <v-alert v-else-if="prdStore.error" type="error" variant="tonal">
      {{ prdStore.error }}
    </v-alert>

    <!-- Content -->
    <template v-else-if="prd">
      <!-- Header -->
      <div class="d-flex align-center ga-3 mb-6">
        <v-btn icon="mdi-arrow-left" variant="text" size="small" @click="$router.push('/prds')" />
        <div class="flex-grow-1">
          <div class="text-caption text-medium-emphasis">
            PRD-{{ String(prd.prd_number).padStart(3, '0') }}
          </div>
          <div v-if="!editingTitle" class="text-h5 font-weight-bold cursor-pointer" @click="startEditTitle">
            {{ prd.title }}
            <v-icon icon="mdi-pencil-outline" size="16" class="ml-1 text-medium-emphasis" />
          </div>
          <v-text-field
            v-else
            v-model="editTitle"
            variant="outlined"
            density="compact"
            autofocus
            hide-details
            class="mt-1"
            style="max-width: 500px;"
            @blur="saveTitle"
            @keyup.enter="saveTitle"
            @keyup.escape="editingTitle = false"
          />
        </div>
        <v-select
          v-model="prd.status"
          :items="statusItems"
          density="compact"
          variant="outlined"
          hide-details
          style="max-width: 160px;"
          @update:model-value="updateStatus"
        />
        <v-btn
          icon="mdi-delete-outline"
          variant="text"
          color="error"
          size="small"
          @click="confirmDelete = true"
        />
      </div>

      <div class="text-caption text-medium-emphasis mb-6">
        Created {{ formatDate(prd.created_at) }} · Updated {{ formatDate(prd.updated_at) }}
      </div>

      <!-- Tabs -->
      <v-tabs v-model="activeTab" color="primary" class="mb-4">
        <v-tab value="requirements">Requirements</v-tab>
        <v-tab value="tech-spec">Tech Spec</v-tab>
        <v-tab value="test-plan">Test Plan</v-tab>
      </v-tabs>

      <v-tabs-window v-model="activeTab">
        <!-- Requirements -->
        <v-tabs-window-item value="requirements">
          <v-card color="surface" class="pa-6">
            <div class="d-flex align-center justify-space-between mb-3">
              <div class="text-body-2 font-weight-medium">Requirements</div>
              <v-btn
                :icon="editingContent ? 'mdi-eye-outline' : 'mdi-pencil-outline'"
                variant="text"
                size="small"
                @click="toggleContentEdit"
              />
            </div>
            <v-textarea
              v-if="editingContent"
              v-model="editContent"
              variant="outlined"
              rows="16"
              placeholder="Write PRD requirements in markdown..."
              hide-details
              class="markdown-editor"
              @blur="saveContent"
            />
            <div v-else class="text-body-2 markdown-preview">
              {{ prd.content_md || 'No requirements written yet. Click the edit icon to start.' }}
            </div>
          </v-card>
        </v-tabs-window-item>

        <!-- Tech Spec -->
        <v-tabs-window-item value="tech-spec">
          <v-card color="surface" class="pa-6">
            <div class="d-flex align-center justify-space-between mb-3">
              <div class="text-body-2 font-weight-medium">Technical Specification</div>
              <v-btn
                :icon="editingTechSpec ? 'mdi-eye-outline' : 'mdi-pencil-outline'"
                variant="text"
                size="small"
                @click="toggleTechSpecEdit"
              />
            </div>
            <v-textarea
              v-if="editingTechSpec"
              v-model="editTechSpec"
              variant="outlined"
              rows="16"
              placeholder="Technical implementation details..."
              hide-details
              class="markdown-editor"
              @blur="saveTechSpec"
            />
            <div v-else class="text-body-2 markdown-preview">
              {{ prd.tech_spec_md || 'No tech spec yet. This can be generated by the Tech Plan Agent.' }}
            </div>
          </v-card>
        </v-tabs-window-item>

        <!-- Test Plan -->
        <v-tabs-window-item value="test-plan">
          <v-card color="surface" class="pa-6">
            <div class="d-flex align-center justify-space-between mb-3">
              <div class="text-body-2 font-weight-medium">Test Plan</div>
              <v-btn
                :icon="editingTestPlan ? 'mdi-eye-outline' : 'mdi-pencil-outline'"
                variant="text"
                size="small"
                @click="toggleTestPlanEdit"
              />
            </div>
            <v-textarea
              v-if="editingTestPlan"
              v-model="editTestPlan"
              variant="outlined"
              rows="16"
              placeholder="Test cases and testing strategy..."
              hide-details
              class="markdown-editor"
              @blur="saveTestPlan"
            />
            <div v-else class="text-body-2 markdown-preview">
              {{ prd.test_plan_md || 'No test plan yet. This can be generated by the Test Plan Agent.' }}
            </div>
          </v-card>
        </v-tabs-window-item>
      </v-tabs-window>
    </template>

    <!-- Delete confirmation -->
    <v-dialog v-model="confirmDelete" max-width="400">
      <v-card color="surface" class="pa-6">
        <div class="text-h6 mb-2">Delete PRD?</div>
        <div class="text-body-2 text-medium-emphasis mb-4">
          This will permanently delete PRD-{{ String(prd?.prd_number || 0).padStart(3, '0') }}: {{ prd?.title }}.
        </div>
        <v-card-actions class="pa-0">
          <v-spacer />
          <v-btn variant="text" @click="confirmDelete = false">Cancel</v-btn>
          <v-btn color="error" variant="flat" @click="handleDelete">Delete</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { usePRDStore } from '@/stores/prd'
import { PRD_STATUS_ORDER, PRD_STATUS_LABELS } from '@/types'

const route = useRoute()
const router = useRouter()
const prdStore = usePRDStore()

const prd = computed(() => prdStore.currentPRD)

const activeTab = ref('requirements')
const confirmDelete = ref(false)

// Title editing
const editingTitle = ref(false)
const editTitle = ref('')

// Content editing
const editingContent = ref(false)
const editContent = ref('')
const editingTechSpec = ref(false)
const editTechSpec = ref('')
const editingTestPlan = ref(false)
const editTestPlan = ref('')

const statusItems = PRD_STATUS_ORDER.map(s => ({
  title: PRD_STATUS_LABELS[s],
  value: s,
}))

onMounted(async () => {
  const id = route.params.id as string
  await prdStore.fetchPRD(id)
})

function startEditTitle(): void {
  editTitle.value = prd.value?.title || ''
  editingTitle.value = true
}

async function saveTitle(): Promise<void> {
  if (!prd.value || !editTitle.value.trim()) {
    editingTitle.value = false
    return
  }
  if (editTitle.value.trim() !== prd.value.title) {
    await prdStore.updatePRD(prd.value.id, { title: editTitle.value.trim() })
  }
  editingTitle.value = false
}

async function updateStatus(newStatus: string): Promise<void> {
  if (!prd.value) return
  await prdStore.updatePRD(prd.value.id, { status: newStatus } as never)
}

function toggleContentEdit(): void {
  if (editingContent.value) {
    saveContent()
  } else {
    editContent.value = prd.value?.content_md || ''
    editingContent.value = true
  }
}

async function saveContent(): Promise<void> {
  if (!prd.value) return
  if (editContent.value !== (prd.value.content_md || '')) {
    await prdStore.updatePRD(prd.value.id, { content_md: editContent.value })
  }
  editingContent.value = false
}

function toggleTechSpecEdit(): void {
  if (editingTechSpec.value) {
    saveTechSpec()
  } else {
    editTechSpec.value = prd.value?.tech_spec_md || ''
    editingTechSpec.value = true
  }
}

async function saveTechSpec(): Promise<void> {
  if (!prd.value) return
  if (editTechSpec.value !== (prd.value.tech_spec_md || '')) {
    await prdStore.updatePRD(prd.value.id, { tech_spec_md: editTechSpec.value })
  }
  editingTechSpec.value = false
}

function toggleTestPlanEdit(): void {
  if (editingTestPlan.value) {
    saveTestPlan()
  } else {
    editTestPlan.value = prd.value?.test_plan_md || ''
    editingTestPlan.value = true
  }
}

async function saveTestPlan(): Promise<void> {
  if (!prd.value) return
  if (editTestPlan.value !== (prd.value.test_plan_md || '')) {
    await prdStore.updatePRD(prd.value.id, { test_plan_md: editTestPlan.value })
  }
  editingTestPlan.value = false
}

async function handleDelete(): Promise<void> {
  if (!prd.value) return
  const ok = await prdStore.deletePRD(prd.value.id)
  if (ok) router.push('/prds')
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}
</script>

<style scoped>
.markdown-preview {
  white-space: pre-wrap;
  line-height: 1.7;
  min-height: 200px;
  color: rgba(var(--v-theme-on-surface), 0.7);
}

.markdown-editor :deep(textarea) {
  font-family: 'JetBrains Mono', 'Fira Code', monospace;
  font-size: 13px;
  line-height: 1.6;
}
</style>
