# Copyright 2025-2026 Arun Rajkumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Async job handler for the bulk GitHub-App repo onboarding flow.

Given a list of ``BulkOnboardItemProgress`` rows (each ``full_name`` +
chosen branches), this handler:

1. Loads the org and fetches a single GitHub-App installation token.
2. Fans out per-item clone+upsert work under a small semaphore.
3. After every item settles, hands the successful repo IDs to the
   shared :func:`kick_off_onboard_scan` helper — the same seam used
   by the wizard's local-path arm.

Per-item progress is streamed through ``update_job`` so the frontend's
``useJobSocket`` consumer can render live status — every flip in
``BulkOnboardItemState`` (``pending → cloning → done|error``) calls
``update_job(result=payload.model_dump(...))``.

**Token security:** the installation token is fetched once at the top
of the handler, passed into ``compose_app_clone_url`` per item, and
never persisted on ``TrackedRepository``. Any stderr / URL string that
might contain the token is run through
:func:`app.services.repo_cloner._sanitize` before logging.

Per-item helpers live in :mod:`job_repo_bulk_clone_helpers` so this
file stays focused on the orchestration shape.
"""

from __future__ import annotations

import asyncio
import uuid
from collections.abc import Awaitable
from typing import Any

import structlog

from app.database import AsyncSessionLocal
from app.repositories.organization import OrganizationRepository
from app.schemas.jobs import (
    BulkOnboardItemState,
    BulkOnboardJobPayload,
    JobState,
)
from app.services.github_app_auth import get_installation_token
from app.services.job_queue import update_job
from app.services.job_repo_bulk_clone_helpers import (
    JOB_PROGRESS_BASE_PCT,
    DbFactory,
    run_with_progress,
    summarise,
)
from app.services.redis_cache import INSTALLABLE_REPOS_KEY_TEMPLATE, delete_key
from app.services.repo_cloner import _sanitize, purge_repo_clones
from app.services.scan.runner import ScanAlreadyActiveError
from app.services.scan_kickoff import kick_off_onboard_scan

logger = structlog.get_logger(__name__)

# ── Module-level constants ─────────────────────────────────────────
BULK_ONBOARD_CONCURRENCY = 4
JOB_PROGRESS_FINAL_PCT = 100

# Friendly user-facing message when the kickoff finds another scan
# already active. Stack traces are unhelpful in the wizard UI; the
# user just needs to know to wait or cancel the running scan.
_ACTIVE_SCAN_MSG = (
    "Another scan is already running for this org; finish or cancel it before re-running setup."
)


async def handle_bulk_onboard_job(
    job_id: str,
    raw_payload: dict[str, Any],
    *,
    db_factory: DbFactory = AsyncSessionLocal,
) -> None:
    """Bulk-clone + register a list of GitHub-App-visible repos, then scan.

    Args:
        job_id: Generated by ``create_job`` and used to publish progress.
        raw_payload: ``BulkOnboardJobPayload.model_dump()`` from the
            endpoint — re-parsed here so the handler always sees a
            validated DTO regardless of whether the queue serialises
            its dicts.
        db_factory: Session factory override for tests.
    """
    payload = BulkOnboardJobPayload(**raw_payload)
    total = len(payload.items)

    update_job(
        job_id,
        status_message="Loading organization...",
        progress_pct=JOB_PROGRESS_BASE_PCT,
        result=payload.model_dump(by_alias=True, mode="json"),
    )

    # Outer session: just for the org load. Closes before we fan out so
    # per-item child sessions don't fight over the same connection.
    async with db_factory() as db:
        org = await OrganizationRepository(db).get_by_id(payload.org_id)

    if org is None:
        update_job(
            job_id,
            state=JobState.FAILED,
            error="Organization not found.",
            status_message="Failed",
        )
        return

    token = await get_installation_token(org)
    if not token:
        update_job(
            job_id,
            state=JobState.FAILED,
            error="GitHub App installation is not ready for this organization.",
            status_message="Failed",
        )
        return

    # Wipe cached clones for the specific repos being re-onboarded so a
    # half-finished prior attempt (interrupted setup, merge conflict,
    # corrupted worktree) can't carry stale state forward. Scoped to the
    # current payload — sibling clones belonging to in-flight scans on
    # OTHER repos are left alone, since wiping them mid-scan rips the
    # working tree out and produces "no source files found" failures.
    update_job(
        job_id,
        status_message="Clearing previous clones...",
        progress_pct=JOB_PROGRESS_BASE_PCT,
        result=payload.model_dump(by_alias=True, mode="json"),
    )
    repo_names = [item.full_name.split("/", 1)[-1] for item in payload.items]
    removed = await asyncio.to_thread(purge_repo_clones, org.slug, repo_names)
    logger.info(
        "bulk_onboard_clones_purged",
        org_slug=org.slug,
        requested=len(repo_names),
        removed=removed,
    )

    semaphore = asyncio.Semaphore(BULK_ONBOARD_CONCURRENCY)
    counter: dict[str, int] = {"done": 0}
    tasks: list[Awaitable[None]] = [
        run_with_progress(
            job_id=job_id,
            payload=payload,
            item=item,
            token=token,
            org_slug=org.slug,
            db_factory=db_factory,
            semaphore=semaphore,
            counter=counter,
            total=total,
        )
        for item in payload.items
    ]
    await asyncio.gather(*tasks)

    successful_repo_ids: list[uuid.UUID] = [
        item.repo_id
        for item in payload.items
        if item.status is BulkOnboardItemState.DONE and item.repo_id is not None
    ]

    # Invalidate the picker's installable-repos cache so freshly-onboarded
    # repos show as ``already_tracked`` immediately on the next page load
    # instead of waiting up to 60s for the TTL.
    if successful_repo_ids:
        await delete_key(INSTALLABLE_REPOS_KEY_TEMPLATE.format(org_id=str(payload.org_id)))

    scan_id: uuid.UUID | None = None
    embedding_warning: str | None = None
    if successful_repo_ids:
        try:
            scan_id, embedding_warning = await kick_off_onboard_scan(
                org_id=payload.org_id,
                repo_ids=successful_repo_ids,
            )
        except ScanAlreadyActiveError:
            logger.warning(
                "bulk_onboard_scan_kickoff_skipped_active",
                org_id=str(payload.org_id),
            )
            update_job(
                job_id,
                state=JobState.FAILED,
                error=_ACTIVE_SCAN_MSG,
                status_message="Scan kickoff skipped",
                result=summarise(payload, scan_id=None),
            )
            return
        except Exception as exc:
            logger.exception("bulk_onboard_scan_kickoff_failed")
            update_job(
                job_id,
                state=JobState.FAILED,
                error=_sanitize(str(exc), token),
                status_message="Scan kickoff failed",
                result=summarise(payload, scan_id=None),
            )
            return

    result = summarise(payload, scan_id=scan_id)
    completion_message = embedding_warning or "Done"
    update_job(
        job_id,
        state=JobState.COMPLETED,
        status_message=completion_message,
        progress_pct=JOB_PROGRESS_FINAL_PCT,
        result=result,
    )
    logger.info(
        "bulk_onboard_job_complete",
        job_id=job_id,
        succeeded=len(result["succeeded"]),
        failed=len(result["failed"]),
        scan_id=result["scan_id"],
        embedding_warning=embedding_warning,
    )
