# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Arun Rajkumar

"""Async job handler for the bulk GitHub-App repo onboarding flow.

Given a list of ``BulkOnboardItemProgress`` rows (each ``full_name`` +
chosen branches), this handler:

1. Loads the org and fetches a single GitHub-App installation token.
2. Fans out per-item clone+upsert work under a small semaphore.
3. After every item settles, kicks off a single v2 scan covering
   the successful repos.

Per-item progress is streamed through ``update_job`` so the frontend's
``useJobSocket`` consumer can render live status — every flip in
``BulkOnboardItemState`` (``pending → cloning → done|error``) calls
``update_job(result=payload.model_dump(...))``.

**Token security:** the installation token is fetched once at the top
of the handler, passed into ``compose_app_clone_url`` per item, and
never persisted on ``TrackedRepository``. Any stderr / URL string that
might contain the token is run through
:func:`app.services.repo_cloner._sanitize` before logging.

Per-item helpers live in :mod:`job_repo_bulk_clone_helpers` so this
file stays focused on the orchestration shape.
"""

from __future__ import annotations

import asyncio
import uuid
from collections.abc import Awaitable
from typing import Any

import structlog

from app.database import AsyncSessionLocal
from app.repositories.organization import OrganizationRepository
from app.schemas.jobs import (
    BulkOnboardItemState,
    BulkOnboardJobPayload,
    JobState,
)
from app.schemas.scan import RunConfig
from app.services.github_app_auth import get_installation_token
from app.services.job_queue import update_job
from app.services.job_repo_bulk_clone_helpers import (
    JOB_PROGRESS_BASE_PCT,
    DbFactory,
    run_with_progress,
    summarise,
)
from app.services.repo_cloner import _sanitize
from app.services.scan.runner import start_v2_scan, wait_for_scan_task

logger = structlog.get_logger(__name__)

# ── Module-level constants ─────────────────────────────────────────
BULK_ONBOARD_CONCURRENCY = 4
JOB_PROGRESS_FINAL_PCT = 100

# When a bulk-onboard run produces many newly-cloned repos, kicking
# off a single ``start_v2_scan`` for all of them lets every scan stage
# (gitnexus indexer, classifier, embedding extraction, …) fan out
# across the whole set in parallel. On a 20-repo onboard that pinned
# CPU and starved unrelated HTTP requests of DB connections. We
# instead chunk the repo_ids into batches and run one scan per batch
# sequentially — each batch's scan task is awaited via
# ``wait_for_scan_task`` before the next batch starts.
BULK_SCAN_BATCH_SIZE = 4


async def handle_bulk_onboard_job(
    job_id: str,
    raw_payload: dict[str, Any],
    *,
    db_factory: DbFactory = AsyncSessionLocal,
) -> None:
    """Bulk-clone + register a list of GitHub-App-visible repos, then scan.

    Args:
        job_id: Generated by ``create_job`` and used to publish progress.
        raw_payload: ``BulkOnboardJobPayload.model_dump()`` from the
            endpoint — re-parsed here so the handler always sees a
            validated DTO regardless of whether the queue serialises
            its dicts.
        db_factory: Session factory override for tests.
    """
    payload = BulkOnboardJobPayload(**raw_payload)
    total = len(payload.items)

    update_job(
        job_id,
        status_message="Loading organization...",
        progress_pct=JOB_PROGRESS_BASE_PCT,
        result=payload.model_dump(by_alias=True, mode="json"),
    )

    # Outer session: just for the org load. Closes before we fan out so
    # per-item child sessions don't fight over the same connection.
    async with db_factory() as db:
        org = await OrganizationRepository(db).get_by_id(payload.org_id)

    if org is None:
        update_job(
            job_id,
            state=JobState.FAILED,
            error="Organization not found.",
            status_message="Failed",
        )
        return

    token = await get_installation_token(org)
    if not token:
        update_job(
            job_id,
            state=JobState.FAILED,
            error="GitHub App installation is not ready for this organization.",
            status_message="Failed",
        )
        return

    semaphore = asyncio.Semaphore(BULK_ONBOARD_CONCURRENCY)
    counter: dict[str, int] = {"done": 0}
    tasks: list[Awaitable[None]] = [
        run_with_progress(
            job_id=job_id,
            payload=payload,
            item=item,
            token=token,
            org_slug=org.slug,
            db_factory=db_factory,
            semaphore=semaphore,
            counter=counter,
            total=total,
        )
        for item in payload.items
    ]
    await asyncio.gather(*tasks)

    successful_repo_ids: list[uuid.UUID] = [
        item.repo_id
        for item in payload.items
        if item.status is BulkOnboardItemState.DONE and item.repo_id is not None
    ]

    scan_ids: list[uuid.UUID] = []
    if successful_repo_ids:
        try:
            scan_ids = await _run_batched_scans(
                org_id=payload.org_id,
                repo_ids=successful_repo_ids,
            )
        except Exception as exc:
            logger.exception("bulk_onboard_scan_kickoff_failed")
            update_job(
                job_id,
                state=JobState.FAILED,
                error=_sanitize(str(exc), token),
                status_message="Scan kickoff failed",
                result=summarise(payload, scan_id=None),
            )
            return

    first_scan_id = scan_ids[0] if scan_ids else None
    result = summarise(payload, scan_id=first_scan_id, scan_ids=scan_ids)
    update_job(
        job_id,
        state=JobState.COMPLETED,
        status_message="Done",
        progress_pct=JOB_PROGRESS_FINAL_PCT,
        result=result,
    )
    logger.info(
        "bulk_onboard_job_complete",
        job_id=job_id,
        succeeded=len(result["succeeded"]),
        failed=len(result["failed"]),
        scan_id=result["scan_id"],
        scan_ids=result["scan_ids"],
    )


def _chunk_repo_ids(
    repo_ids: list[uuid.UUID],
    batch_size: int,
) -> list[list[uuid.UUID]]:
    """Split ``repo_ids`` into contiguous chunks of at most ``batch_size``."""
    if batch_size <= 0:
        raise ValueError("batch_size must be a positive integer")
    return [repo_ids[i : i + batch_size] for i in range(0, len(repo_ids), batch_size)]


async def _run_batched_scans(
    *,
    org_id: uuid.UUID,
    repo_ids: list[uuid.UUID],
) -> list[uuid.UUID]:
    """Kick off one scan per ``BULK_SCAN_BATCH_SIZE``-chunk of repos, in series.

    Each batch's scan task is awaited to natural completion via
    :func:`wait_for_scan_task` before the next batch starts. This caps
    the number of repos any scan stage runs concurrently at
    ``BULK_SCAN_BATCH_SIZE`` without requiring a sweeping change inside
    the scan runner.
    """
    scan_ids: list[uuid.UUID] = []
    for batch in _chunk_repo_ids(repo_ids, BULK_SCAN_BATCH_SIZE):
        scan_id = await start_v2_scan(
            org_id=org_id,
            repo_ids=batch,
            config=RunConfig(),
        )
        scan_ids.append(scan_id)
        # Block until this batch's background task finishes before the
        # next batch is scheduled. ``start_v2_scan`` is fire-and-forget,
        # so without this wait we'd be back to fully-concurrent fanout.
        await wait_for_scan_task(scan_id)
    return scan_ids
