"""add bud priority enum and column

Revision ID: 022576f6a3c9
Revises: e177cbfa9580
Create Date: 2026-05-27 16:30:47.277629

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "022576f6a3c9"
down_revision: str | None = "e177cbfa9580"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bud_priority = sa.Enum("P0", "P1", "P2", "P3", name="bud_priority")
    bud_priority.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "bud_documents",
        sa.Column(
            "priority",
            sa.Enum("P0", "P1", "P2", "P3", name="bud_priority", create_type=False),
            server_default="P2",
            nullable=False,
        ),
    )
    op.create_index("ix_bud_org_priority", "bud_documents", ["org_id", "priority"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bud_org_priority", table_name="bud_documents")
    op.drop_column("bud_documents", "priority")
    sa.Enum(name="bud_priority").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
