# Copyright 2025-2026 Arun Rajkumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add_pull_requests_and_github_fields

Revision ID: 2cd5153962b3
Revises: 07eecbe67e31
Create Date: 2026-03-29 15:13:27.075157

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cd5153962b3"
down_revision: str | None = "07eecbe67e31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_requests",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("bud_id", sa.UUID(), nullable=True),
        sa.Column("repo_id", sa.UUID(), nullable=True),
        sa.Column("github_pr_number", sa.Integer(), nullable=False),
        sa.Column("github_pr_id", sa.BigInteger(), nullable=False),
        sa.Column("github_repo_full_name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("html_url", sa.String(length=1000), nullable=False),
        sa.Column("head_branch", sa.String(length=255), nullable=False),
        sa.Column("base_branch", sa.String(length=255), nullable=False),
        sa.Column("state", sa.Enum("open", "closed", "merged", name="pr_state"), nullable=False),
        sa.Column("author_github_login", sa.String(length=100), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("pending", "approved", "changes_requested", name="pr_review_status"),
            nullable=False,
        ),
        sa.Column("metadata_", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["bud_id"], ["bud_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["tracked_repositories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "github_pr_id", name="uq_pr_org_github_id"),
    )
    op.create_index("ix_pr_bud_id", "pull_requests", ["bud_id"], unique=False)
    op.create_index("ix_pr_org_state", "pull_requests", ["org_id", "state"], unique=False)
    op.drop_index("ix_bud_chat_session", table_name="bud_chat_messages")
    op.drop_index("ix_prd_documents_org_id", table_name="bud_documents")
    op.drop_index("ix_dev_activity_bud_event_type", table_name="dev_activity_logs")
    op.drop_index(
        "uq_dev_activity_org_commit_sha",
        table_name="dev_activity_logs",
        postgresql_where="(((event_type)::text = 'commit'::text) AND (commit_sha IS NOT NULL))",
    )
    op.drop_index("ix_krl_knowledge_id", table_name="knowledge_to_repo")
    op.add_column("organizations", sa.Column("github_webhook_secret", sa.Text(), nullable=True))
    op.drop_index("ix_sp_feature_id", table_name="skill_profiles")
    op.add_column(
        "tracked_repositories",
        sa.Column("github_repo_full_name", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_tracked_repositories_github_repo_full_name"),
        "tracked_repositories",
        ["github_repo_full_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tracked_repositories_github_repo_full_name"), table_name="tracked_repositories"
    )
    op.drop_column("tracked_repositories", "github_repo_full_name")
    op.create_index("ix_sp_feature_id", "skill_profiles", ["feature_id"], unique=False)
    op.drop_column("organizations", "github_webhook_secret")
    op.create_index("ix_krl_knowledge_id", "knowledge_to_repo", ["knowledge_id"], unique=False)
    op.create_index(
        "uq_dev_activity_org_commit_sha",
        "dev_activity_logs",
        ["org_id", "commit_sha"],
        unique=True,
        postgresql_where="(((event_type)::text = 'commit'::text) AND (commit_sha IS NOT NULL))",
    )
    op.create_index(
        "ix_dev_activity_bud_event_type",
        "dev_activity_logs",
        ["bud_id", "event_type"],
        unique=False,
    )
    op.create_index("ix_prd_documents_org_id", "bud_documents", ["org_id"], unique=False)
    op.create_index(
        "ix_bud_chat_session", "bud_chat_messages", ["bud_id", "session_id"], unique=False
    )
    op.drop_index("ix_pr_org_state", table_name="pull_requests")
    op.drop_index("ix_pr_bud_id", table_name="pull_requests")
    op.drop_table("pull_requests")
    # ### end Alembic commands ###
