# Copyright 2025-2026 Arun Rajkumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add skill_points house_level vehicle_unlocks to developer_xp

Revision ID: 3922c4bb35ad
Revises: 18bb5e095ca2
Create Date: 2026-04-12 19:50:14.247138

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3922c4bb35ad"
down_revision: str | None = "18bb5e095ca2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_bugs_bud_id"), "bugs", ["bud_id"], unique=False)
    op.add_column(
        "developer_xp",
        sa.Column(
            "skill_points",
            sa.Numeric(precision=10, scale=2, asdecimal=False),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "developer_xp", sa.Column("house_level", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "developer_xp",
        sa.Column(
            "vehicle_unlocks",
            postgresql.ARRAY(sa.String(length=30)),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("developer_xp", "vehicle_unlocks")
    op.drop_column("developer_xp", "house_level")
    op.drop_column("developer_xp", "skill_points")
    op.drop_index(op.f("ix_bugs_bud_id"), table_name="bugs")
    # ### end Alembic commands ###
