"""add branch_overrides to bud_documents

Revision ID: 3c40529301a3
Revises: a9a073feecb7
Create Date: 2026-06-02 22:37:03.430575

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c40529301a3"
down_revision: str | None = "a9a073feecb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bud_documents",
        sa.Column("branch_overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bud_documents", "branch_overrides")
    # ### end Alembic commands ###
