# Copyright 2025-2026 Arun Rajkumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""initial schema

Revision ID: 42c23bf48e1d
Revises:
Create Date: 2026-03-15 23:39:13.125286

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector  # noqa: F401
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42c23bf48e1d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # PostgreSQL extensions required by the schema
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("github_app_token", sa.Text(), nullable=True),
        sa.Column("slack_bot_token", sa.Text(), nullable=True),
        sa.Column("slack_signing_secret", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "agent_logs",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=255), nullable=False),
        sa.Column("trigger_type", sa.String(length=100), nullable=True),
        sa.Column("trigger_source", sa.String(length=255), nullable=True),
        sa.Column("input_summary", sa.Text(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("execution_time_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_logs_org_id"), "agent_logs", ["org_id"], unique=False)
    op.create_table(
        "code_embeddings",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("repo", sa.String(length=500), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("function_name", sa.String(length=500), nullable=True),
        sa.Column("content_summary", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_embeddings_org_id"), "code_embeddings", ["org_id"], unique=False)
    op.create_table(
        "enterprise_rules",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enterprise_rules_org_id"),
        "enterprise_rules",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "prd_documents",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("prd_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "design",
                "tech-spec",
                "in-dev",
                "in-qa",
                "in-uat",
                "deployed",
                name="prd_status",
            ),
            nullable=False,
        ),
        sa.Column("content_md", sa.Text(), nullable=True),
        sa.Column("tech_spec_md", sa.Text(), nullable=True),
        sa.Column("test_plan_md", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "prd_number", name="uq_prd_org_number"),
    )
    op.create_index(op.f("ix_prd_documents_org_id"), "prd_documents", ["org_id"], unique=False)
    op.create_table(
        "standup_reports",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("posted_to_slack_ts", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "date", name="uq_standup_org_date"),
    )
    op.create_index(op.f("ix_standup_reports_org_id"), "standup_reports", ["org_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "org_owner",
                "admin",
                "pm",
                "tech_lead",
                "developer",
                "designer",
                "qa",
                "support",
                "viewer",
                name="user_role",
            ),
            nullable=False,
        ),
        sa.Column("slack_id", sa.String(length=50), nullable=True),
        sa.Column("github_username", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email", name="uq_users_org_email"),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "bugs",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("prd_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="bug_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "in-progress", "resolved", "closed", "blocked", name="bug_status"),
            nullable=False,
        ),
        sa.Column("module", sa.String(length=255), nullable=True),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("linked_pr", sa.String(length=500), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prd_id"],
            ["prd_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bugs_org_id"), "bugs", ["org_id"], unique=False)
    op.create_table(
        "execution_nodes",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("lan_ip", sa.String(length=45), nullable=True),
        sa.Column("tailscale_ip", sa.String(length=45), nullable=True),
        sa.Column("advertised_url", sa.String(length=500), nullable=True),
        sa.Column("health_port", sa.Integer(), nullable=False),
        sa.Column("execution_mode", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("discovery_method", sa.String(length=50), nullable=True),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cli_version", sa.String(length=50), nullable=True),
        sa.Column("os_info", sa.String(length=255), nullable=True),
        sa.Column("max_concurrent", sa.Integer(), nullable=False),
        sa.Column("repos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("node_token_hash", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_task_count", sa.Integer(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("ram_percent", sa.Float(), nullable=True),
        sa.Column("total_tasks_completed", sa.Integer(), nullable=False),
        sa.Column("total_tasks_failed", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_execution_nodes_org_id"), "execution_nodes", ["org_id"], unique=False)
    op.create_table(
        "feature_learnings",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("prd_id", sa.UUID(), nullable=False),
        sa.Column("cycle_time_days", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("estimated_days", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("bug_count", sa.Integer(), nullable=False),
        sa.Column("retrospective_md", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prd_id"],
            ["prd_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feature_learnings_org_id"),
        "feature_learnings",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "jwt_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jwt_tokens_org_id"), "jwt_tokens", ["org_id"], unique=False)
    op.create_index(op.f("ix_jwt_tokens_user_id"), "jwt_tokens", ["user_id"], unique=False)
    op.create_table(
        "knowledge_items",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("source_ref", sa.String(length=500), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_items_org_id"), "knowledge_items", ["org_id"], unique=False)
    op.create_table(
        "org_memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "org_owner",
                "admin",
                "pm",
                "tech_lead",
                "developer",
                "designer",
                "qa",
                "support",
                "viewer",
                name="user_role",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "org_id", name="uq_org_memberships_user_org"),
    )
    op.create_index(op.f("ix_org_memberships_org_id"), "org_memberships", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_org_memberships_user_id"),
        "org_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "skill_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=255), nullable=False),
        sa.Column("repo", sa.String(length=500), nullable=True),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("skill_score", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("touch_count", sa.Integer(), nullable=False),
        sa.Column("last_touch", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "org_id", "module", name="uq_skill_user_org_module"),
    )
    op.create_index(op.f("ix_skill_profiles_org_id"), "skill_profiles", ["org_id"], unique=False)
    op.create_index(op.f("ix_skill_profiles_user_id"), "skill_profiles", ["user_id"], unique=False)

    # HNSW vector indexes for semantic search (cosine distance)
    op.execute(
        "CREATE INDEX ix_prd_documents_embedding ON prd_documents "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_code_embeddings_embedding ON code_embeddings "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_knowledge_items_embedding ON knowledge_items "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_bugs_embedding ON bugs "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_enterprise_rules_embedding ON enterprise_rules "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute(
        "CREATE INDEX ix_feature_learnings_embedding ON feature_learnings "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop HNSW vector indexes
    op.execute("DROP INDEX IF EXISTS ix_feature_learnings_embedding")
    op.execute("DROP INDEX IF EXISTS ix_enterprise_rules_embedding")
    op.execute("DROP INDEX IF EXISTS ix_bugs_embedding")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_items_embedding")
    op.execute("DROP INDEX IF EXISTS ix_code_embeddings_embedding")
    op.execute("DROP INDEX IF EXISTS ix_prd_documents_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skill_profiles_user_id"), table_name="skill_profiles")
    op.drop_index(op.f("ix_skill_profiles_org_id"), table_name="skill_profiles")
    op.drop_table("skill_profiles")
    op.drop_index(op.f("ix_org_memberships_user_id"), table_name="org_memberships")
    op.drop_index(op.f("ix_org_memberships_org_id"), table_name="org_memberships")
    op.drop_table("org_memberships")
    op.drop_index(op.f("ix_knowledge_items_org_id"), table_name="knowledge_items")
    op.drop_table("knowledge_items")
    op.drop_index(op.f("ix_jwt_tokens_user_id"), table_name="jwt_tokens")
    op.drop_index(op.f("ix_jwt_tokens_org_id"), table_name="jwt_tokens")
    op.drop_table("jwt_tokens")
    op.drop_index(op.f("ix_feature_learnings_org_id"), table_name="feature_learnings")
    op.drop_table("feature_learnings")
    op.drop_index(op.f("ix_execution_nodes_org_id"), table_name="execution_nodes")
    op.drop_table("execution_nodes")
    op.drop_index(op.f("ix_bugs_org_id"), table_name="bugs")
    op.drop_table("bugs")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_standup_reports_org_id"), table_name="standup_reports")
    op.drop_table("standup_reports")
    op.drop_index(op.f("ix_prd_documents_org_id"), table_name="prd_documents")
    op.drop_table("prd_documents")
    op.drop_index(op.f("ix_enterprise_rules_org_id"), table_name="enterprise_rules")
    op.drop_table("enterprise_rules")
    op.drop_index(op.f("ix_code_embeddings_org_id"), table_name="code_embeddings")
    op.drop_table("code_embeddings")
    op.drop_index(op.f("ix_agent_logs_org_id"), table_name="agent_logs")
    op.drop_table("agent_logs")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
