"""add user notification_prefs

Revision ID: 49ab39f82371
Revises: eb58f3fd77ba
Create Date: 2026-06-14 21:33:48.264176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ab39f82371'
down_revision: Union[str, None] = 'eb58f3fd77ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_prefs')
    # ### end Alembic commands ###
