"""triage_sessions bud_id ondelete set null

Revision ID: 5aa33f92b7bd
Revises: f0e2e3aaf8d6
Create Date: 2026-05-25 22:32:51.585609

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5aa33f92b7bd'
down_revision: str | None = 'f0e2e3aaf8d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'triage_sessions_bud_id_fkey', 'triage_sessions', type_='foreignkey'
    )
    op.create_foreign_key(
        None,
        'triage_sessions',
        'bud_documents',
        ['bud_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'triage_sessions', type_='foreignkey')
    op.create_foreign_key(
        'triage_sessions_bud_id_fkey',
        'triage_sessions',
        'bud_documents',
        ['bud_id'],
        ['id'],
    )
    # ### end Alembic commands ###
