"""drop setup_last_error debug column

Revision ID: 7155600b973a
Revises: zal_tracked_repos_setup_err
Create Date: 2026-05-07 22:26:23.024889

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7155600b973a"
down_revision: str | None = "zal_tracked_repos_setup_err"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_repositories", "setup_last_error")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_repositories",
        sa.Column("setup_last_error", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
