"""add_code_review_comments_column

Revision ID: 75212a109582
Revises: 9c58acc3643d
Create Date: 2026-04-03 22:27:35.724957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75212a109582"
down_revision: str | None = "9c58acc3643d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bud_documents",
        sa.Column("code_review_comments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bud_documents", "code_review_comments")
    # ### end Alembic commands ###
