# Copyright 2025-2026 Arun Rajkumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add unique partial index on xp_events source_ref

Revision ID: 9c58acc3643d
Revises: f498ce391075
Create Date: 2026-04-02 10:42:53.728257

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c58acc3643d"
down_revision: str | None = "f498ce391075"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_xp_events_source_ref", table_name="xp_events")
    op.create_index(
        "uq_xp_events_source_ref",
        "xp_events",
        ["source_ref", "org_id"],
        unique=True,
        postgresql_where="source_ref IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_xp_events_source_ref",
        table_name="xp_events",
        postgresql_where="source_ref IS NOT NULL",
    )
    op.create_index("ix_xp_events_source_ref", "xp_events", ["source_ref"], unique=False)
    # ### end Alembic commands ###
