"""add unique partial index on xp_events source_ref

Revision ID: 9c58acc3643d
Revises: f498ce391075
Create Date: 2026-04-02 10:42:53.728257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c58acc3643d'
down_revision: Union[str, None] = 'f498ce391075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xp_events_source_ref', table_name='xp_events')
    op.create_index('uq_xp_events_source_ref', 'xp_events', ['source_ref', 'org_id'], unique=True, postgresql_where='source_ref IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_xp_events_source_ref', table_name='xp_events', postgresql_where='source_ref IS NOT NULL')
    op.create_index('ix_xp_events_source_ref', 'xp_events', ['source_ref'], unique=False)
    # ### end Alembic commands ###
