"""add resume_session_id to bud_agent_tasks

Revision ID: 9d9cbba60038
Revises: fc38aad10a53
Create Date: 2026-05-26 13:40:46.868688

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d9cbba60038'
down_revision: str | None = 'fc38aad10a53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bud_agent_tasks', sa.Column('resume_session_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bud_agent_tasks', 'resume_session_id')
    # ### end Alembic commands ###
