"""add_bud_estimates_and_snapshots

Revision ID: 9e6edbdfee20
Revises: f9ba2fdeac07
Create Date: 2026-04-01 15:46:26.531848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e6edbdfee20"
down_revision: str | None = "f9ba2fdeac07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bud_estimate_snapshots",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("bud_id", sa.UUID(), nullable=False),
        sa.Column("trigger", sa.String(length=30), nullable=False),
        sa.Column("phase_estimates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("complexity", sa.Integer(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["bud_id"], ["bud_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bud_estimate_snapshot_bud_id", "bud_estimate_snapshots", ["bud_id"], unique=False
    )
    op.create_index(
        op.f("ix_bud_estimate_snapshots_org_id"),
        "bud_estimate_snapshots",
        ["org_id"],
        unique=False,
    )
    op.add_column(
        "bud_documents",
        sa.Column("estimated_dates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("bud_documents", sa.Column("complexity", sa.Integer(), nullable=True))
    op.add_column(
        "bud_documents", sa.Column("prod_p70_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "bud_documents",
        sa.Column("current_phase_deadline", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_bud_phase_deadline",
        "bud_documents",
        ["org_id", "current_phase_deadline"],
        unique=False,
    )
    op.create_index("ix_bud_prod_p70", "bud_documents", ["org_id", "prod_p70_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bud_prod_p70", table_name="bud_documents")
    op.drop_index("ix_bud_phase_deadline", table_name="bud_documents")
    op.drop_column("bud_documents", "current_phase_deadline")
    op.drop_column("bud_documents", "prod_p70_date")
    op.drop_column("bud_documents", "complexity")
    op.drop_column("bud_documents", "estimated_dates")
    op.drop_index(op.f("ix_bud_estimate_snapshots_org_id"), table_name="bud_estimate_snapshots")
    op.drop_index("ix_bud_estimate_snapshot_bud_id", table_name="bud_estimate_snapshots")
    op.drop_table("bud_estimate_snapshots")
    # ### end Alembic commands ###
