"""add minigame_scores table

Revision ID: 9fa5f815b7e6
Revises: ade529ed6144
Create Date: 2026-06-12 23:41:04.166821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fa5f815b7e6"
down_revision: Union[str, None] = "ade529ed6144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "minigame_scores",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("game", sa.String(), nullable=False),
        sa.Column("best_score", sa.Integer(), nullable=False),
        sa.Column("plays", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("last_played_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "game", name="uq_minigame_scores_user_game"),
    )
    op.create_index(
        "ix_minigame_scores_org_game_best",
        "minigame_scores",
        ["org_id", "game", "best_score"],
        unique=False,
    )
    op.create_index(op.f("ix_minigame_scores_org_id"), "minigame_scores", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_minigame_scores_user_id"), "minigame_scores", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_minigame_scores_user_id"), table_name="minigame_scores")
    op.drop_index(op.f("ix_minigame_scores_org_id"), table_name="minigame_scores")
    op.drop_index("ix_minigame_scores_org_game_best", table_name="minigame_scores")
    op.drop_table("minigame_scores")
    # ### end Alembic commands ###
