"""feature_learnings_metrics_column

Revision ID: af5af83d4327
Revises: 0adad4d4dd8d
Create Date: 2026-05-30 21:39:11.914718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5af83d4327'
down_revision: Union[str, None] = '0adad4d4dd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_learnings', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_learnings', 'metrics')
    # ### end Alembic commands ###
