"""add minigame_sessions idempotency table

Revision ID: c323d36aa5f3
Revises: 49ab39f82371
Create Date: 2026-06-15 16:58:17.711819

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c323d36aa5f3"
down_revision: str | None = "49ab39f82371"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "minigame_sessions",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("game", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", name="uq_minigame_sessions_session_id"),
    )
    op.create_index(
        op.f("ix_minigame_sessions_org_id"), "minigame_sessions", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_minigame_sessions_user_id"), "minigame_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_minigame_sessions_user_id"), table_name="minigame_sessions")
    op.drop_index(op.f("ix_minigame_sessions_org_id"), table_name="minigame_sessions")
    op.drop_table("minigame_sessions")
    # ### end Alembic commands ###
