"""add cli_model to feature_qa_sessions

Revision ID: c8c8c14dc765
Revises: f06f6340e5ae
Create Date: 2026-06-10 09:54:21.657026

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8c8c14dc765"
down_revision: str | None = "f06f6340e5ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_qa_sessions", sa.Column("cli_model", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature_qa_sessions", "cli_model")
    # ### end Alembic commands ###
