"""add iteration_max_turns to agent_skills

Revision ID: d8fa5f485b44
Revises: e5c377b7f95e
Create Date: 2026-06-04 15:49:27.760766

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8fa5f485b44"
down_revision: str | None = "e5c377b7f95e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_skills",
        sa.Column(
            "iteration_max_turns",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_skills", "iteration_max_turns")
    # ### end Alembic commands ###
