"""skill_profile add lines_added lines_removed

Revision ID: e177cbfa9580
Revises: 9d9cbba60038
Create Date: 2026-05-26 21:31:39.732442

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e177cbfa9580'
down_revision: str | None = '9d9cbba60038'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' backfills existing rows so the NOT NULL add
    # succeeds; new rows still get the application-side default of 0
    # from the SQLAlchemy model.
    op.add_column(
        'skill_profiles',
        sa.Column('lines_added', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'skill_profiles',
        sa.Column('lines_removed', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_profiles', 'lines_removed')
    op.drop_column('skill_profiles', 'lines_added')
    # ### end Alembic commands ###
