"""add bug.feature_id and bug_comments

Revision ID: e5c377b7f95e
Revises: 3c40529301a3
Create Date: 2026-06-03 20:57:35.508253

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5c377b7f95e"
down_revision: str | None = "3c40529301a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bug_comments",
        sa.Column("bug_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["bug_id"], ["bugs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bug_comments_bug_created", "bug_comments", ["bug_id", "created_at"], unique=False
    )
    op.create_index("ix_bug_comments_org", "bug_comments", ["org_id"], unique=False)
    op.add_column("bugs", sa.Column("feature_id", sa.UUID(), nullable=True))
    op.create_index("ix_bugs_feature_id_status", "bugs", ["feature_id", "status"], unique=False)
    op.create_foreign_key(
        "fk_bugs_feature_id", "bugs", "features", ["feature_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_bugs_feature_id", "bugs", type_="foreignkey")
    op.drop_index("ix_bugs_feature_id_status", table_name="bugs")
    op.drop_column("bugs", "feature_id")
    op.drop_index("ix_bug_comments_org", table_name="bug_comments")
    op.drop_index("ix_bug_comments_bug_created", table_name="bug_comments")
    op.drop_table("bug_comments")
    # ### end Alembic commands ###
