"""company quiz game

Revision ID: eb58f3fd77ba
Revises: 9fa5f815b7e6
Create Date: 2026-06-14 15:53:44.312191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb58f3fd77ba'
down_revision: Union[str, None] = '9fa5f815b7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', 'used', name='quiz_question_status'), nullable=False),
    sa.Column('question_type', sa.Enum('multiple_choice', 'scramble', 'fill_blank', name='quiz_question_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'mixed', name='quiz_difficulty'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('topic_hash', sa.String(length=64), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_job_id', sa.String(length=64), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name='fk_quiz_questions_approved_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_org_id'), 'quiz_questions', ['org_id'], unique=False)
    op.create_index('ix_quiz_questions_org_status', 'quiz_questions', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_quiz_questions_topic_hash'), 'quiz_questions', ['topic_hash'], unique=False)
    op.create_table('quiz_scores',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_answered', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.BigInteger(), nullable=False),
    sa.Column('quizzes_played', sa.Integer(), nullable=False),
    sa.Column('participation_streak', sa.Integer(), nullable=False),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('last_quiz_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_month', name='uq_quiz_scores_user_month')
    )
    op.create_index(op.f('ix_quiz_scores_org_id'), 'quiz_scores', ['org_id'], unique=False)
    op.create_index('ix_quiz_scores_org_month_points', 'quiz_scores', ['org_id', 'period_month', 'total_points'], unique=False)
    op.create_index(op.f('ix_quiz_scores_user_id'), 'quiz_scores', ['user_id'], unique=False)
    op.create_table('quiz_topic_history',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('topic_hash', sa.String(length=64), nullable=False),
    sa.Column('topic_label', sa.String(length=255), nullable=False),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'topic_hash', name='uq_quiz_topic_org_hash')
    )
    op.create_index(op.f('ix_quiz_topic_history_org_id'), 'quiz_topic_history', ['org_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('quiz_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'revealed', name='quiz_status'), nullable=False),
    sa.Column('open_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reveal_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'quiz_date', name='uq_quizzes_org_date')
    )
    op.create_index(op.f('ix_quizzes_org_id'), 'quizzes', ['org_id'], unique=False)
    op.create_index('ix_quizzes_org_status', 'quizzes', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_quizzes_question_id'), 'quizzes', ['question_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_quiz_answers_user_question')
    )
    op.create_index(op.f('ix_quiz_answers_org_id'), 'quiz_answers', ['org_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_quiz_id'), 'quiz_answers', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_answers_quiz_user', 'quiz_answers', ['quiz_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_user_id'), 'quiz_answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_user_id'), table_name='quiz_answers')
    op.drop_index('ix_quiz_answers_quiz_user', table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_quiz_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_org_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quizzes_question_id'), table_name='quizzes')
    op.drop_index('ix_quizzes_org_status', table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_org_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_quiz_topic_history_org_id'), table_name='quiz_topic_history')
    op.drop_table('quiz_topic_history')
    op.drop_index(op.f('ix_quiz_scores_user_id'), table_name='quiz_scores')
    op.drop_index('ix_quiz_scores_org_month_points', table_name='quiz_scores')
    op.drop_index(op.f('ix_quiz_scores_org_id'), table_name='quiz_scores')
    op.drop_table('quiz_scores')
    op.drop_index(op.f('ix_quiz_questions_topic_hash'), table_name='quiz_questions')
    op.drop_index('ix_quiz_questions_org_status', table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_org_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    # Drop the enum types so a re-upgrade can recreate them cleanly.
    op.execute('DROP TYPE IF EXISTS quiz_status')
    op.execute('DROP TYPE IF EXISTS quiz_difficulty')
    op.execute('DROP TYPE IF EXISTS quiz_question_type')
    op.execute('DROP TYPE IF EXISTS quiz_question_status')
    # ### end Alembic commands ###
