"""add bud_feature_link table

Revision ID: ed5143cd2646
Revises: 7155600b973a
Create Date: 2026-05-11 15:33:29.565338

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed5143cd2646"
down_revision: str | None = "7155600b973a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bud_feature_link",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bud_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column(
            "link_type",
            sa.Enum("touches", "depends_on", name="bud_feature_link_type"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("pm_agent", "manual", "tech_arch", name="bud_feature_link_source"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bud_id"], ["bud_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bud_id", "feature_id", name="uq_bfl_bud_feature"),
    )
    op.create_index("ix_bfl_bud_id", "bud_feature_link", ["bud_id"], unique=False)
    op.create_index("ix_bfl_feature_id", "bud_feature_link", ["feature_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bfl_feature_id", table_name="bud_feature_link")
    op.drop_index("ix_bfl_bud_id", table_name="bud_feature_link")
    op.drop_table("bud_feature_link")
    # ### end Alembic commands ###
