"""feature qa sessions

Revision ID: f0e2e3aaf8d6
Revises: 746af40a95ec
Create Date: 2026-05-25 16:06:22.300140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0e2e3aaf8d6"
down_revision: str | None = "746af40a95ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_qa_sessions",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("thread_ts", sa.String(length=50), nullable=False),
        sa.Column("requester_slack_user_id", sa.String(length=50), nullable=False),
        sa.Column("original_question", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("awaiting_user", "resolved", "errored", name="feature_qa_status"),
            nullable=False,
        ),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "channel", "thread_ts", name="uq_fqa_org_thread"),
    )
    op.create_index(
        op.f("ix_feature_qa_sessions_org_id"),
        "feature_qa_sessions",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        "ix_fqa_org_status",
        "feature_qa_sessions",
        ["org_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fqa_org_status", table_name="feature_qa_sessions")
    op.drop_index(
        op.f("ix_feature_qa_sessions_org_id"),
        table_name="feature_qa_sessions",
    )
    op.drop_table("feature_qa_sessions")
    # ### end Alembic commands ###
