# Copyright 2025-2026 Arun Rajkumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add developer_xp and xp_events tables

Revision ID: f498ce391075
Revises: 9e6edbdfee20
Create Date: 2026-04-02 10:26:38.421921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f498ce391075"
down_revision: str | None = "9e6edbdfee20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "developer_xp",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("level_name", sa.String(length=30), nullable=False),
        sa.Column("streak_count", sa.Integer(), nullable=False),
        sa.Column("last_active_date", sa.Date(), nullable=True),
        sa.Column("streak_best", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "org_id", name="uq_xp_user_org"),
    )
    op.create_index("ix_xp_org_leaderboard", "developer_xp", ["org_id", "total_xp"], unique=False)
    op.create_index("ix_xp_org_level", "developer_xp", ["org_id", "level"], unique=False)
    op.create_table(
        "xp_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("xp_amount", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("multiplier", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("metadata_", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_xp_events_org_time", "xp_events", ["org_id", "created_at"], unique=False)
    op.create_index("ix_xp_events_source_ref", "xp_events", ["source_ref"], unique=False)
    op.create_index(
        "ix_xp_events_user_org_time",
        "xp_events",
        ["user_id", "org_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_xp_events_user_org_time", table_name="xp_events")
    op.drop_index("ix_xp_events_source_ref", table_name="xp_events")
    op.drop_index("ix_xp_events_org_time", table_name="xp_events")
    op.drop_table("xp_events")
    op.drop_index("ix_xp_org_level", table_name="developer_xp")
    op.drop_index("ix_xp_org_leaderboard", table_name="developer_xp")
    op.drop_table("developer_xp")
    # ### end Alembic commands ###
