"""replace_github_pat_with_app_credentials

Revision ID: f9ba2fdeac07
Revises: 2cd5153962b3
Create Date: 2026-03-29 16:00:02.433143

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9ba2fdeac07"
down_revision: str | None = "2cd5153962b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("github_app_id", sa.Integer(), nullable=True))
    op.add_column("organizations", sa.Column("github_app_private_key", sa.Text(), nullable=True))
    op.add_column(
        "organizations", sa.Column("github_app_installation_id", sa.Integer(), nullable=True)
    )
    op.drop_column("organizations", "github_pat")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("github_pat", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("organizations", "github_app_installation_id")
    op.drop_column("organizations", "github_app_private_key")
    op.drop_column("organizations", "github_app_id")
    # ### end Alembic commands ###
